### ISSUE TITLE
gen_hop1 and gen_hop2 are very slow

### ISSUE THREAD

**Issue by aagohary** [qipeng/golden-retriever#13]
Hi, Thanks for the great work. 
I followed the exact same setup instructions in the readme, but I found that gen_hop1 and gen_hop2 are very slow, each takes > 4 days when run on the training set .. is that something I should expect? or I am missing something about the installation? Thanks!

-Ahmed

**Comment by qipeng** [comment]
You should be able to speed things up significantly if you have many CPU cores and allowed elasticsearch/the scripts to use all of them. Larger RAM allocation for elasticsearch is also beneficial. But yeah this process is slow in general because it requires repeated queries to elasticsearch.
