### ISSUE TITLE
warn about running setup.sh in docker

### ISSUE THREAD

**Issue by Phirefly9** [qipeng/golden-retriever#2]
if you run setup.sh in docker without entering the container as a non root user, elasticsearch will silently fail to launch and setup.sh will get stuck waiting in an infinite loop for elasticsearch to come up.

Another option would be to have setup.sh check if the script is run from the root user and refuse to run.

**Comment by qipeng** [comment]
Thank you for your report! Just another data point for non-docker users: we were able to run this script fine without root privileges in Ubuntu and MacOS...
