### ISSUE TITLE
WARN: Duplicate embedding found for

### ISSUE THREAD

**Issue by anushkmittal** [qipeng/golden-retriever#5]
i get a lot of `[ WARN: Duplicate embedding found for Protección ]` warnings with words like these that have accents. is this expected?

**Comment by luxuantao** [comment]
> i get a lot of `[ WARN: Duplicate embedding found for Protección ]` warnings with words like these that have accents. is this expected?

I met the same problem

**Comment by qipeng** [comment]
This is expected (and is from the open-source DrQA code). :)
