### ISSUE TITLE
what's a good way to run an interactive shell like DrQA offers?

### ISSUE THREAD

**Issue by anushkmittal** [qipeng/golden-retriever#6]
I'm still trying to make sense of the bash script...

Do you have any tips on how to get that input sentence, get model output interactive behavior...

**Comment by qipeng** [comment]
Unfortunately we don't have an interactive mode just yet, but for each example, running something similar to the end-to-end bash script is probably going to achieve just that. The bash script is just chaining all of the components in our pipeline as described in the paper. :)

**Comment by anushkmittal** [comment]
can you help me identify which script / python file should I be executing to run the prediction or "test" code...

Modifying input data into `end_to_ennd_eval` makes it want to do "train" steps.. which I don't need for just predicting answers.

**Comment by anushkmittal** [comment]
also, is your script expecting full Wikipedia as context?

I know your paper reads that you're working on full-wiki setting i.e. finding answer to the question by querying the entirety of wiki dump but hotpot QA data appears to be structured such that it's giving you contextual paragraphs linked with each question such that at least for the initial hop, you're expecting that rather than querying the entire Wikipedia...

**Comment by qipeng** [comment]
Yes, our script expects the entire Wikipedia as context and doesn't use hyperlink information to target HotpotQA. `scripts/eval_end_to_end.sh` should be what you want for generating predictions, and please follow our README to set up the environment.
