### ISSUE TITLE
what is start_mapping?

### ISSUE THREAD

**Issue by mehdimashayekhi** [qipeng/golden-retriever#7]
Hi, thanks for sharing your code. I have a question about ```start_mapping``` shape [batch_size, max_sent_cnt, NUM_OF_PARAGRAPHS * MAX_PARAGRAPH_LEN)], and I have trouble understanding these lines here : https://github.com/qipeng/golden-retriever/blob/c806574a373a4ee86b7e754f169bb2a54d3ba15f/BiDAFpp/model.py#L96 and here https://github.com/qipeng/golden-retriever/blob/c806574a373a4ee86b7e754f169bb2a54d3ba15f/BiDAFpp/model.py#L97 I really appreciate your response

**Comment by qipeng** [comment]
These are just mapping (copying) indices of words in paragraphs (start and end of each sentence) to a sentence representation.

**Comment by mehdimashayekhi** [comment]
thanks for your reply, sorry for multiple questions, then what is ```all_mapping``` and why do you multiply it with ```sp_output```? https://github.com/qipeng/golden-retriever/blob/c806574a373a4ee86b7e754f169bb2a54d3ba15f/BiDAFpp/model.py#L103

**Comment by qipeng** [comment]
This is just mapping sentence representations back to each token for concatenation.
