### ISSUE TITLE
pexpect.exceptions.TIMEOUT

### ISSUE THREAD

**Issue by qiunlp** [qipeng/golden-retriever#8]
bash scripts/eval_end_to_end.sh

当运行其中的：python ${DRQA_DIR}/scripts/reader/predict.py $OUTDIR/hop1_squadified.json --out-dir $OUTDIR --num-workers $NUM_DRQA_WORKERS --embedding-file $EMBED_FILE --model $HOP1_MODEL_FILE

执行到   DrQA/drqa/reader/predictor.py
        if self.workers:
              q_tokens = self.workers.map_async(tokenize, questions)
不停报错：
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 26665
child_fd: 20
closed: False
timeout: 60

**Comment by qipeng** [comment]
This is probably due to an incorrect setup of DrQA, especially the CoreNLP component in it. Could you try following DrQA's instructions to set things up again? See https://github.com/facebookresearch/DrQA

**Comment by qiunlp** [comment]
Thank you!
